#!/bin/bash
#
# Script for building and running unit tests
#
# To Execute: 
#     bash goserv
#
# NOTE: This file must be converted to use Linux line ending characters
# using the following before it will run correctly:
#     dos2unix goserv

echo Launching server...
bash gradlew run
